name: Pets Management Deploy

on:
  push:
    branches:
    - master
    paths:
    - 'petsmanagement/**'

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: petsmanagement
  GKE_REGION: europe-west1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '275.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}

    - name: Set up docker to authenticate
      run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud components install beta
        gcloud auth configure-docker

    - name: Build docker image
      run: |
        docker build -t gcr.io/"$GKE_PROJECT"/"$IMAGE":"$GITHUB_SHA" \
          -f petsmanagement/Dockerfile .

    - name: Push the Docker image to Google Container Registry
      run: |
        docker push gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA

    - name: Deploy service to Cloud Run
      run: |
        gcloud beta run deploy petsmanagement-api \
          --image "gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA" \
          --project "$GKE_PROJECT" \
          --region "$GKE_REGION" \
          --platform managed \
          --allow-unauthenticated \
          --args=api \
          --command=/petsmanagement \
          --memory=128Mi
